name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: install hatch
        run: pip install hatch
      - run: |
          set DISTUTILS_USE_SDK=1
          set MSSdk=1
          git clone https://github.com/pygame/pygame.git
          cd pygame
          python -m pip install setuptools requests -U
          python -m buildconfig -sdl2 --download
      - name: build
        run: hatch run build
      - run: ls dist
