name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.8'
      - name: install hatch
        run: pip install hatch
      - name: build
        run: pyinstaller portal_space/cli/__main__.py
      - run: ls dist
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: portal-space
          path: dist/portal-space
