name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - name: Set up Python
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.x'
      - name: install hatch
        run: pip install hatch
      - name: build
        run: hatch run build
      - run: ls dist
